pip install numpy


In [3]:
import numpy as np


In [4]:
n1 = np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
x = []
len(dir(x))

47

In [6]:
len(dir(n1))

165

In [7]:
n1.shape

(4,)

In [8]:
n2 = np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


Creating matrix
- arange
- linspace
- random.rand
- random.randn
- random.randint
- eye
- ones 
- zeros

In [9]:
x = np.arange(-10,10,.2)
x.shape

(100,)

In [10]:
y = np.linspace(1,5,10)
print(y)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [11]:
np.random.rand(3,3)

array([[0.59531856, 0.67775948, 0.39518831],
       [0.10846541, 0.00742319, 0.78773264],
       [0.76432539, 0.92036433, 0.75306185]])

In [12]:
np.random.randn(10)

array([ 0.45436761,  1.26531166, -0.39503484,  0.97672989,  0.15461178,
        1.23864745,  1.96361017, -1.58817246,  1.24901171,  0.19887484])

In [13]:
np.random.randint(1,5,(5,5))

array([[2, 4, 1, 3, 4],
       [1, 3, 1, 2, 2],
       [2, 2, 4, 4, 4],
       [4, 2, 2, 4, 2],
       [1, 3, 3, 1, 3]])

In [14]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(3,2))
print(x)
print(y)

[[7 1]
 [8 9]
 [3 2]]
[[1 8]
 [6 3]
 [4 1]]


In [15]:
x + 5

array([[12,  6],
       [13, 14],
       [ 8,  7]])

In [16]:
x + y

array([[ 8,  9],
       [14, 12],
       [ 7,  3]])

In [17]:
x * y

array([[ 7,  8],
       [48, 27],
       [12,  2]])

In [18]:
x.dot(y.T)

array([[15, 45, 29],
       [80, 75, 41],
       [19, 24, 14]])

In [19]:
np.sin(x)

array([[0.6569866 , 0.84147098],
       [0.98935825, 0.41211849],
       [0.14112001, 0.90929743]])

In [20]:
print(x.sum())
print(x.mean())
print(x.std())


30
5.0
3.1091263510296048


In [42]:
a = np.linspace(0,5,50)
print(a)
print(a.shape)
a2 = a.reshape(10,5)
print(a2)
print(a2.shape)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]
(50,)
[[0.         0.10204082 0.20408163 0.30612245 0.40816327]
 [0.51020408 0.6122449  0.71428571 0.81632653 0.91836735]
 [1.02040816 1.12244898 1.2244898  1.32653061 1.42857143]
 [1.53061224 1.63265306 1.73469388 1.83673469 1.93877551]
 [2.04081633 2.14285714 2.24489796 2.34693878 2.44897959]
 [2.55102041 2.65306122 2.75510204 2.85714286 2.95918367]
 [3.06122449 3.16326531 3.26530612 3.36734694 3.46938776]
 [3.57142857 3.67346939 3.77

In [43]:
a2.reshape(50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [44]:
m = np.random.randint(1,10,(10,10))
print(m)

[[7 3 8 8 2 2 6 5 3 7]
 [1 4 6 9 8 4 2 8 3 5]
 [1 9 8 5 7 1 7 1 7 5]
 [6 5 2 7 7 2 5 8 9 4]
 [4 9 6 4 4 8 9 7 8 9]
 [5 3 9 4 8 8 1 1 1 3]
 [9 6 6 7 3 5 9 2 1 8]
 [3 7 9 3 1 3 8 1 1 9]
 [6 6 9 6 5 9 4 6 2 8]
 [9 6 8 7 1 8 9 8 5 4]]


In [45]:
print(m[0,0])
print(m[0,-1])
print(m[-1,0])
print(m[-1,-1])
print(m[2,5])
print(m[3,3])

7
7
9
4
1
7


In [49]:
print(m[0])
print(m[1])
print(m[-1])
print(m[:3])
print(m[-3:])

[7 3 8 8 2 2 6 5 3 7]
[1 4 6 9 8 4 2 8 3 5]
[9 6 8 7 1 8 9 8 5 4]
[[7 3 8 8 2 2 6 5 3 7]
 [1 4 6 9 8 4 2 8 3 5]
 [1 9 8 5 7 1 7 1 7 5]]
[[3 7 9 3 1 3 8 1 1 9]
 [6 6 9 6 5 9 4 6 2 8]
 [9 6 8 7 1 8 9 8 5 4]]


In [53]:
print(m[:,0])                     # first column
print(m[:,-1])                    # last column
print(m[:,:3])                    # first 3 column
print(m[:,-3:])                   # last 3 column

[7 1 1 6 4 5 9 3 6 9]
[7 5 5 4 9 3 8 9 8 4]
[[7 3 8]
 [1 4 6]
 [1 9 8]
 [6 5 2]
 [4 9 6]
 [5 3 9]
 [9 6 6]
 [3 7 9]
 [6 6 9]
 [9 6 8]]
[[5 3 7]
 [8 3 5]
 [1 7 5]
 [8 9 4]
 [7 8 9]
 [1 1 3]
 [2 1 8]
 [1 1 9]
 [6 2 8]
 [8 5 4]]


In [54]:
print(m[:,[0,2,3,5]])

[[7 8 8 2]
 [1 6 9 4]
 [1 8 5 1]
 [6 2 7 2]
 [4 6 4 8]
 [5 9 4 8]
 [9 6 7 5]
 [3 9 3 3]
 [6 9 6 9]
 [9 8 7 8]]


filtering

In [55]:
m<5   # boolean filter

array([[False,  True, False, False,  True,  True, False, False,  True,
        False],
       [ True,  True, False, False, False,  True,  True, False,  True,
        False],
       [ True, False, False, False, False,  True, False,  True, False,
        False],
       [False, False,  True, False, False,  True, False, False, False,
         True],
       [ True, False, False,  True,  True, False, False, False, False,
        False],
       [False,  True, False,  True, False, False,  True,  True,  True,
         True],
       [False, False, False, False,  True, False, False,  True,  True,
        False],
       [ True, False, False,  True,  True,  True, False,  True,  True,
        False],
       [False, False, False, False, False, False,  True, False,  True,
        False],
       [False, False, False, False,  True, False, False, False, False,
         True]])

In [56]:
m[m<5]

array([3, 2, 2, 3, 1, 4, 4, 2, 3, 1, 1, 1, 2, 2, 4, 4, 4, 4, 3, 4, 1, 1,
       1, 3, 3, 2, 1, 3, 3, 1, 3, 1, 1, 4, 2, 1, 4])

In [57]:
m[m>3]

array([7, 8, 8, 6, 5, 7, 4, 6, 9, 8, 4, 8, 5, 9, 8, 5, 7, 7, 7, 5, 6, 5,
       7, 7, 5, 8, 9, 4, 4, 9, 6, 4, 4, 8, 9, 7, 8, 9, 5, 9, 4, 8, 8, 9,
       6, 6, 7, 5, 9, 8, 7, 9, 8, 9, 6, 6, 9, 6, 5, 9, 4, 6, 8, 9, 6, 8,
       7, 8, 9, 8, 5, 4])

In [59]:
m[(m >= 3) & (m <= 6)]

array([3, 6, 5, 3, 4, 6, 4, 3, 5, 5, 5, 6, 5, 5, 4, 4, 6, 4, 4, 5, 3, 4,
       3, 6, 6, 3, 5, 3, 3, 3, 6, 6, 6, 5, 4, 6, 6, 5, 4])