pip install numpy


In [7]:
import numpy as np


In [8]:
n1 = np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [11]:
x = []
len(dir(x))

47

In [12]:
len(dir(n1))

165

In [13]:
n1.shape

(4,)

In [14]:
n2 = np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


Creating matrix
- arange
- linspace
- random.rand
- random.randn
- random.randint
- eye
- ones 
- zeros

In [18]:
x = np.arange(-10,10,.2)
x.shape

(100,)

In [20]:
y = np.linspace(1,5,10)
print(y)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [26]:
np.random.rand(3,3)

array([[0.30396499, 0.75620686, 0.26957176],
       [0.17552544, 0.45389763, 0.90481718],
       [0.95982726, 0.81677142, 0.87278599]])

In [23]:
np.random.randn(10)

array([ 0.18891127,  0.47433001, -0.53842591,  0.03660677, -0.07557519,
        0.39308667,  0.94671023,  1.48627776, -0.99903369,  0.04709136])

In [28]:
np.random.randint(1,5,(5,5))

array([[4, 2, 4, 3, 1],
       [3, 1, 2, 1, 4],
       [3, 4, 4, 4, 4],
       [1, 1, 4, 3, 4],
       [3, 2, 1, 2, 2]])

In [29]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(3,2))
print(x)
print(y)

[[7 5]
 [4 1]
 [3 5]]
[[9 6]
 [3 7]
 [9 9]]


In [30]:
x + 5

array([[12, 10],
       [ 9,  6],
       [ 8, 10]])

In [31]:
x + y

array([[16, 11],
       [ 7,  8],
       [12, 14]])

In [32]:
x * y

array([[63, 30],
       [12,  7],
       [27, 45]])

In [34]:
x.dot(y.T)

array([[ 93,  56, 108],
       [ 42,  19,  45],
       [ 57,  44,  72]])

In [36]:
np.sin(x)

array([[ 0.6569866 , -0.95892427],
       [-0.7568025 ,  0.84147098],
       [ 0.14112001, -0.95892427]])

In [38]:
print(x.sum())
print(x.mean())
print(x.std())


25
4.166666666666667
1.8633899812498247
